### ISSUE TITLE
Readme info + doesnt seem to work

### ISSUE THREAD

**Issue by rainergeis** [pawREP/ACVIEmblemCreator#1]
Thanks for the awesome tool

The readme should specify that the save file and jsons need to go in the same directory as the tool, otherwise it will say yabber is not found in the working directory. 
After you drag the save file and jsons on the tool, it will spit out the USER_DATA files, but not yabber them for the end user. 
I yabbered the folder with the provided version of Yabber, and launched the game with the modified sl2, but I don't see any new decals. Not sure if I did something wrong.

**Comment by rainergeis** [comment]
Update: worth noting that the webapp and desktop client for Geometrize have very slightly different JSONs. The desktop client will wrap all the JSON with 
{"shapes":
>>json info here<<
}

while the webapp does not. I tried removing that additional text with no luck.

**Comment by CandyCodeRal** [comment]
Yeah I got the same issue too, Probably needs a fix.

**Comment by CandyCodeRal** [comment]
Nevermind got it to work, It spits back a .bak file you have to replace with the one already in the save folder then it should show up in the custom image section under user 4

**Comment by rainergeis** [comment]
You have to replace the .bak file? wat. The normal save files are byte for byte the same before and after using the tool btw.

**Comment by CandyCodeRal** [comment]
I dont know if your doing it right or its a one off for me but ill try to explain better. In my save folder I found AC60000.sl2 and AC60000.sl2.bak, I downloaded a JSON file from a image i made from the link provided in the devs explanation. Then put the JSON and only the AC60000.sl2 file in the same folder as EmblemImporter.exe. Then opened the JSON and AC6000.sl2 file with the exe. It would spit me back a AC60000.sl2.bak file, and I selected both the file it spit me back plus my original save AC60000.sl2 and dragged them back to the game save folder replacing the AC60000.sl2.bak that was in there already. Sorry for any bad grammar and how long it is I just wanted to make it as super clear as im able to.

**Comment by CandyCodeRal** [comment]
Also to add I myself didnt need to use anything in the yabber folder to make it work.

**Comment by CandyCodeRal** [comment]
Also Also saw the mod was flag on nexusmods for some reason so be aware

**Comment by Andagualh** [comment]
> Also Also saw the mod was flag on nexusmods for some reason so be aware

The mod was flagged since some vendors do identify the ensambled executable as a trojan. Has anyone thoroughly inspected the code? It's not like we cannot build this ourselves to check.

**Comment by rainergeis** [comment]
> Also to add I myself didnt need to use anything in the yabber folder to make it work.

Yeah mine doesn't spit out the bak file. I wonder if there's some kind of framework or something that I need. ![image](https://github.com/pawREP/ACVIEmblemCreator/assets/113161253/37cfd8fd-a216-4bb5-93bf-28edf213c160)

**Comment by rainergeis** [comment]
> > Also Also saw the mod was flag on nexusmods for some reason so be aware
> 
> 
> 
> The mod was flagged since some antivirus vendors do identify the ensambled executable as a trojan. Has anyone thoroughly inspected the code? It's not like we cannot build this ourselves to check.

Nexus and windows think everything is a Trojan plus I trust b3. Not worried about this.

**Comment by CandyCodeRal** [comment]
> 

I cant make anything like this myself but to what i know there is source code provided if anyone is code competent enough to check it

**Comment by CandyCodeRal** [comment]
> Yeah mine doesn't spit out the bak file. I wonder if there's some kind of framework or something that I need.

No clue, what does it give you back after you execute your save and JSON?
