### ISSUE TITLE
[FR] Importing from save

### ISSUE THREAD

**Issue by God-damnit-all** [pawREP/ACVIEmblemCreator#10]
This might be an odd request, but would you consider a feature for importing emblems from saves, including ones that have been downloaded through share codes?

**Comment by pawREP** [comment]
I won't implement import from another save file but I might add a feature to move downloaded emblems to the user tab so they become available while playing offline.

**Comment by God-damnit-all** [comment]
@pawREP I really think you should reconsider, FROM has been removing a whole lot of shared emblems since 1.04, like this one for example: https://ac-companion.app/posts/46

Lost to the sands of time.
