### ISSUE TITLE
Insufficient number of arguments

### ISSUE THREAD

**Issue by SGINAWAY** [pawREP/ACVIEmblemCreator#3]
I got this caution when I opened it ."Insufficient number of arguments"
What should I do?

**Comment by pawREP** [comment]
[Read the instructions carefully.](https://github.com/pawREP/ACVIEmblemCreator#how-to-use)
 If you get this error you probably double clicked the exe instead of following the instructions. To pack an emblem you should select a save file (.sl2) and at least one json and drag them on the exe.
