### ISSUE TITLE
Background of transparent images is black

### ISSUE THREAD

**Issue by IceDBorn** [pawREP/ACVIEmblemCreator#6]
Is there a way to keep the transparency of images using the provided website?

**Comment by pawREP** [comment]
The website currently doesn't support transparency unfortunately. For now the best options is to replace the background of an image with the color of your armored core before processing. In the medium term I hope to replacing the need for the website with my own, more flexible, tool.

**Comment by IceDBorn** [comment]
You can add a command line option that ignores shapes with a color of `0,0,0`. I can try implementing that tomorrow.

**Comment by pawREP** [comment]
The latest gui release now supports chroma keying which allows easy and interactive background removal. The option to not generate a background to begin with is still in the works but chroma keying should be a good option for most cases.

**Comment by IceDBorn** [comment]
That's great!
