### ISSUE TITLE
im a noob to dis spaces stuff

### ISSUE THREAD

**Issue by Racallio-Ryndoon** [pawREP/ACVIEmblemCreator#8]
okay in version 1.05 I tried changing the spaces in the sl2 file by going into notepad++ and removing spaces but it didn't work if anyone can give me a way to remove spaces in the sl2 file so the emblem creator can actually run, yes I've done all the instructions before I'm just getting the spaces sl2 error message. Maybe its a simple fix idk  somehow I don't know how  to remove spaces but yea 

![Screenshot 2023-09-07 133924](https://github.com/pawREP/ACVIEmblemCreator/assets/144347547/666ad680-d56d-4a9c-9b0f-634a6c811f30)

**Comment by pawREP** [comment]
It's "no spaces in the **file path**", not "no spaces in the **file**". Moving your save file into some folder that doesn't have any spaces in the path should fix this issue.
